/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Alert {
    /// Mission to be completed to earn the reward
    #[serde(rename = "mission")]
    pub mission: Box<models::Mission>,
    #[serde(rename = "rewardTypes")]
    pub reward_types: Vec<models::RewardType>,
}

impl Alert {
    pub fn new(mission: models::Mission, reward_types: Vec<models::RewardType>) -> Alert {
        Alert {
            mission: Box::new(mission),
            reward_types,
        }
    }
}

