/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Arbitration {
    /// unique identifier for this object/event/thing
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// ISO-8601 formatted timestamp for when the event began
    #[serde(rename = "activation", skip_serializing_if = "Option::is_none")]
    pub activation: Option<String>,
    /// A timestamp in ISO 8601 format (YYYY-MM-DDTHH:MM:SSZ) representing a specific point in time. This format is commonly used in APIs to ensure consistent date and time representation. The timestamp is in UTC (Coordinated Universal Time) and does not include any timezone offset. It is used to represent events, deadlines, or any time-related information in a standardized way. Example: \"2023-10-01T12:00:00Z\" represents October 1, 2023, at 12:00 PM UTC. 
    #[serde(rename = "expiry", skip_serializing_if = "Option::is_none")]
    pub expiry: Option<String>,
    /// Plain name for the node
    #[serde(rename = "node", skip_serializing_if = "Option::is_none")]
    pub node: Option<String>,
    /// Localized faction name
    #[serde(rename = "enemy", skip_serializing_if = "Option::is_none")]
    pub enemy: Option<models::Faction>,
    /// Non-localized faction name
    #[serde(rename = "enemyKey", skip_serializing_if = "Option::is_none")]
    pub enemy_key: Option<models::Faction>,
    /// Mission type localized
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Non-localized mission type key
    #[serde(rename = "typeKey", skip_serializing_if = "Option::is_none")]
    pub type_key: Option<models::MissionType>,
    /// Whether this mission requires archwing
    #[serde(rename = "archwing", skip_serializing_if = "Option::is_none")]
    pub archwing: Option<bool>,
    /// Whether this mission requires sharkwing
    #[serde(rename = "sharkwing", skip_serializing_if = "Option::is_none")]
    pub sharkwing: Option<bool>,
}

impl Arbitration {
    pub fn new() -> Arbitration {
        Arbitration {
            id: None,
            activation: None,
            expiry: None,
            node: None,
            enemy: None,
            enemy_key: None,
            r#type: None,
            type_key: None,
            archwing: None,
            sharkwing: None,
        }
    }
}

