/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CetusCycle {
    /// unique identifier for this object/event/thing
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// ISO-8601 formatted timestamp for when the event began
    #[serde(rename = "activation", skip_serializing_if = "Option::is_none")]
    pub activation: Option<String>,
    /// A timestamp in ISO 8601 format (YYYY-MM-DDTHH:MM:SSZ) representing a specific point in time. This format is commonly used in APIs to ensure consistent date and time representation. The timestamp is in UTC (Coordinated Universal Time) and does not include any timezone offset. It is used to represent events, deadlines, or any time-related information in a standardized way. Example: \"2023-10-01T12:00:00Z\" represents October 1, 2023, at 12:00 PM UTC. 
    #[serde(rename = "expiry", skip_serializing_if = "Option::is_none")]
    pub expiry: Option<String>,
    #[serde(rename = "isDay")]
    pub is_day: bool,
    /// Describes the current time. e.g. \"day\" or \"night\"
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(rename = "timeLeft")]
    pub time_left: String,
    #[serde(rename = "isCetus")]
    pub is_cetus: bool,
    /// A short description of the remaining time until the next day/night change.
    #[serde(rename = "shortString", skip_serializing_if = "Option::is_none")]
    pub short_string: Option<String>,
}

impl CetusCycle {
    pub fn new(is_day: bool, time_left: String, is_cetus: bool) -> CetusCycle {
        CetusCycle {
            id: None,
            activation: None,
            expiry: None,
            is_day,
            state: None,
            time_left,
            is_cetus,
            short_string: None,
        }
    }
}

