/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConclaveModes {
    #[serde(rename = "PVPMODE_ALL")]
    pub pvpmode_all: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "PVPMODE_TEAMDEATHMATCH")]
    pub pvpmode_teamdeathmatch: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "PVPMODE_NONE")]
    pub pvpmode_none: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "PVPMODE_CAPTURETHEFLAG")]
    pub pvpmode_capturetheflag: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "PVPMODE_SPEEDBALL")]
    pub pvpmode_speedball: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "PVPMODE_DEATHMATCH")]
    pub pvpmode_deathmatch: Box<models::ConclaveModesPvpmodeAll>,
}

impl ConclaveModes {
    pub fn new(pvpmode_all: models::ConclaveModesPvpmodeAll, pvpmode_teamdeathmatch: models::ConclaveModesPvpmodeAll, pvpmode_none: models::ConclaveModesPvpmodeAll, pvpmode_capturetheflag: models::ConclaveModesPvpmodeAll, pvpmode_speedball: models::ConclaveModesPvpmodeAll, pvpmode_deathmatch: models::ConclaveModesPvpmodeAll) -> ConclaveModes {
        ConclaveModes {
            pvpmode_all: Box::new(pvpmode_all),
            pvpmode_teamdeathmatch: Box::new(pvpmode_teamdeathmatch),
            pvpmode_none: Box::new(pvpmode_none),
            pvpmode_capturetheflag: Box::new(pvpmode_capturetheflag),
            pvpmode_speedball: Box::new(pvpmode_speedball),
            pvpmode_deathmatch: Box::new(pvpmode_deathmatch),
        }
    }
}

