/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Conclave {
    #[serde(rename = "modes")]
    pub modes: Box<models::ConclaveModes>,
    #[serde(rename = "categories")]
    pub categories: Box<models::ConclaveCategories>,
}

impl Conclave {
    pub fn new(modes: models::ConclaveModes, categories: models::ConclaveCategories) -> Conclave {
        Conclave {
            modes: Box::new(modes),
            categories: Box::new(categories),
        }
    }
}

