/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DailyStanding {
    #[serde(rename = "daily", skip_serializing_if = "Option::is_none")]
    pub daily: Option<i32>,
    #[serde(rename = "conclave", skip_serializing_if = "Option::is_none")]
    pub conclave: Option<i32>,
    #[serde(rename = "simaris", skip_serializing_if = "Option::is_none")]
    pub simaris: Option<i32>,
    #[serde(rename = "ostrons", skip_serializing_if = "Option::is_none")]
    pub ostrons: Option<i32>,
    #[serde(rename = "quills", skip_serializing_if = "Option::is_none")]
    pub quills: Option<i32>,
    #[serde(rename = "solaris", skip_serializing_if = "Option::is_none")]
    pub solaris: Option<i32>,
    #[serde(rename = "ventKids", skip_serializing_if = "Option::is_none")]
    pub vent_kids: Option<i32>,
    #[serde(rename = "voxSolaris", skip_serializing_if = "Option::is_none")]
    pub vox_solaris: Option<i32>,
    #[serde(rename = "entrati", skip_serializing_if = "Option::is_none")]
    pub entrati: Option<i32>,
    #[serde(rename = "necraloid", skip_serializing_if = "Option::is_none")]
    pub necraloid: Option<i32>,
    #[serde(rename = "holdfasts", skip_serializing_if = "Option::is_none")]
    pub holdfasts: Option<i32>,
    #[serde(rename = "kahl", skip_serializing_if = "Option::is_none")]
    pub kahl: Option<i32>,
    #[serde(rename = "cavia", skip_serializing_if = "Option::is_none")]
    pub cavia: Option<i32>,
}

impl DailyStanding {
    pub fn new() -> DailyStanding {
        DailyStanding {
            daily: None,
            conclave: None,
            simaris: None,
            ostrons: None,
            quills: None,
            solaris: None,
            vent_kids: None,
            vox_solaris: None,
            entrati: None,
            necraloid: None,
            holdfasts: None,
            kahl: None,
            cavia: None,
        }
    }
}

