/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventAllOfInterimSteps {
    /// Score to each to achieve this step
    #[serde(rename = "goal", skip_serializing_if = "Option::is_none")]
    pub goal: Option<f64>,
    #[serde(rename = "reward", skip_serializing_if = "Option::is_none")]
    pub reward: Option<Box<models::Reward>>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<Box<models::EventAllOfMessage>>,
    /// Suspected to be the number of persons who have completed this step.
    #[serde(rename = "winnerCount", skip_serializing_if = "Option::is_none")]
    pub winner_count: Option<f64>,
}

impl EventAllOfInterimSteps {
    pub fn new() -> EventAllOfInterimSteps {
        EventAllOfInterimSteps {
            goal: None,
            reward: None,
            message: None,
            winner_count: None,
        }
    }
}

