/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventAllOfProgressSteps {
    /// Steps in the progress to completion
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Percent progress to completion
    #[serde(rename = "progressAmt", skip_serializing_if = "Option::is_none")]
    pub progress_amt: Option<f64>,
}

impl EventAllOfProgressSteps {
    pub fn new() -> EventAllOfProgressSteps {
        EventAllOfProgressSteps {
            r#type: None,
            progress_amt: None,
        }
    }
}

