/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Factions : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Factions {
    #[serde(rename = "FC_GRINEER")]
    pub fc_grineer: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "FC_CORPUS")]
    pub fc_corpus: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "FC_INFESTATION")]
    pub fc_infestation: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "FC_CORRUPTED")]
    pub fc_corrupted: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "FC_OROKIN")]
    pub fc_orokin: Box<models::ConclaveModesPvpmodeAll>,
}

impl Factions {
    /// 
    pub fn new(fc_grineer: models::ConclaveModesPvpmodeAll, fc_corpus: models::ConclaveModesPvpmodeAll, fc_infestation: models::ConclaveModesPvpmodeAll, fc_corrupted: models::ConclaveModesPvpmodeAll, fc_orokin: models::ConclaveModesPvpmodeAll) -> Factions {
        Factions {
            fc_grineer: Box::new(fc_grineer),
            fc_corpus: Box::new(fc_corpus),
            fc_infestation: Box::new(fc_infestation),
            fc_corrupted: Box::new(fc_corrupted),
            fc_orokin: Box::new(fc_orokin),
        }
    }
}

