/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FissureModifiers : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FissureModifiers {
    #[serde(rename = "VoidT1")]
    pub void_t1: Box<models::FissureModifiersVoidT1>,
    #[serde(rename = "VoidT2")]
    pub void_t2: Box<models::FissureModifiersVoidT1>,
    #[serde(rename = "VoidT3")]
    pub void_t3: Box<models::FissureModifiersVoidT1>,
    #[serde(rename = "VoidT4")]
    pub void_t4: Box<models::FissureModifiersVoidT1>,
}

impl FissureModifiers {
    /// 
    pub fn new(void_t1: models::FissureModifiersVoidT1, void_t2: models::FissureModifiersVoidT1, void_t3: models::FissureModifiersVoidT1, void_t4: models::FissureModifiersVoidT1) -> FissureModifiers {
        FissureModifiers {
            void_t1: Box::new(void_t1),
            void_t2: Box::new(void_t2),
            void_t3: Box::new(void_t3),
            void_t4: Box::new(void_t4),
        }
    }
}

