/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FissureModifiersVoidT1 {
    #[serde(rename = "num")]
    pub num: f64,
    #[serde(rename = "value")]
    pub value: String,
}

impl FissureModifiersVoidT1 {
    pub fn new(num: f64, value: String) -> FissureModifiersVoidT1 {
        FissureModifiersVoidT1 {
            num,
            value,
        }
    }
}

