/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvasionAllOfAttacker {
    #[serde(rename = "reward", skip_serializing_if = "Option::is_none")]
    pub reward: Option<Box<models::Reward>>,
    /// Localized name of fation
    #[serde(rename = "faction", skip_serializing_if = "Option::is_none")]
    pub faction: Option<models::Faction>,
    /// Unlocalized name of faction
    #[serde(rename = "factionKey", skip_serializing_if = "Option::is_none")]
    pub faction_key: Option<models::Faction>,
}

impl InvasionAllOfAttacker {
    pub fn new() -> InvasionAllOfAttacker {
        InvasionAllOfAttacker {
            reward: None,
            faction: None,
            faction_key: None,
        }
    }
}

