/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoudoutSecondaryInner {
    #[serde(rename = "itemId", skip_serializing_if = "Option::is_none")]
    pub item_id: Option<String>,
    #[serde(rename = "uniqueName", skip_serializing_if = "Option::is_none")]
    pub unique_name: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "nemesis", skip_serializing_if = "Option::is_none")]
    pub nemesis: Option<String>,
    #[serde(rename = "configs", skip_serializing_if = "Option::is_none")]
    pub configs: Option<Vec<models::ConfigsInner>>,
    #[serde(rename = "upgradeFingerprint", skip_serializing_if = "Option::is_none")]
    pub upgrade_fingerprint: Option<Box<models::ProfileWeaponUpgradeFingerprint>>,
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<f64>,
    #[serde(rename = "upgradeVer", skip_serializing_if = "Option::is_none")]
    pub upgrade_ver: Option<i32>,
    #[serde(rename = "xp", skip_serializing_if = "Option::is_none")]
    pub xp: Option<i32>,
    #[serde(rename = "polarized", skip_serializing_if = "Option::is_none")]
    pub polarized: Option<i32>,
    #[serde(rename = "polarity", skip_serializing_if = "Option::is_none")]
    pub polarity: Option<Vec<models::ProfileWeaponPolarityInner>>,
    #[serde(rename = "item", skip_serializing_if = "Option::is_none")]
    pub item: Option<Box<models::RangedWeapon>>,
}

impl LoudoutSecondaryInner {
    pub fn new() -> LoudoutSecondaryInner {
        LoudoutSecondaryInner {
            item_id: None,
            unique_name: None,
            name: None,
            nemesis: None,
            configs: None,
            upgrade_fingerprint: None,
            features: None,
            upgrade_ver: None,
            xp: None,
            polarized: None,
            polarity: None,
            item: None,
        }
    }
}

