/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Mission {
    #[serde(rename = "reward")]
    pub reward: Box<models::Reward>,
    #[serde(rename = "node")]
    pub node: String,
    /// Unlocalized node
    #[serde(rename = "nodeKey", skip_serializing_if = "Option::is_none")]
    pub node_key: Option<String>,
    /// Mission opponent (localized)
    #[serde(rename = "faction")]
    pub faction: models::Faction,
    /// Mission opponent (unlocalized)
    #[serde(rename = "factionKey", skip_serializing_if = "Option::is_none")]
    pub faction_key: Option<models::Faction>,
    #[serde(rename = "maxEnemyLevel")]
    pub max_enemy_level: f64,
    #[serde(rename = "minEnemyLevel")]
    pub min_enemy_level: f64,
    #[serde(rename = "maxWaveNum")]
    pub max_wave_num: f64,
    /// Mission objective type (localized)
    #[serde(rename = "type")]
    pub r#type: models::MissionType,
    /// Mission objective type (unlocalized)
    #[serde(rename = "typeKey", skip_serializing_if = "Option::is_none")]
    pub type_key: Option<models::MissionType>,
    #[serde(rename = "nightmare")]
    pub nightmare: bool,
    /// Whether an Archwing is required for participating in the mision.
    #[serde(rename = "archwingRequired")]
    pub archwing_required: bool,
    /// Whether the mission takes place in a submerssible mission.
    #[serde(rename = "isSharkwing", skip_serializing_if = "Option::is_none")]
    pub is_sharkwing: Option<bool>,
    /// Enemy specification for the mission
    #[serde(rename = "enemySpec", skip_serializing_if = "Option::is_none")]
    pub enemy_spec: Option<String>,
    /// Override for the map on this mission
    #[serde(rename = "levelOverride", skip_serializing_if = "Option::is_none")]
    pub level_override: Option<String>,
    /// Array of strings denoting extra spawners for a mission
    #[serde(rename = "advancedSpawners", skip_serializing_if = "Option::is_none")]
    pub advanced_spawners: Option<Vec<String>>,
    /// Items required to enter the mission
    #[serde(rename = "requiredItems", skip_serializing_if = "Option::is_none")]
    pub required_items: Option<Vec<String>>,
    /// Whether the required items are consumed
    #[serde(rename = "consumeRequiredItems", skip_serializing_if = "Option::is_none")]
    pub consume_required_items: Option<bool>,
    /// Whether leaders are always allowed
    #[serde(rename = "leadersAlwaysAllowed", skip_serializing_if = "Option::is_none")]
    pub leaders_always_allowed: Option<bool>,
    /// Affectors for this mission
    #[serde(rename = "levelAuras", skip_serializing_if = "Option::is_none")]
    pub level_auras: Option<Vec<String>>,
    /// Description of the mission
    #[serde(rename = "description")]
    pub description: String,
}

impl Mission {
    pub fn new(reward: models::Reward, node: String, faction: models::Faction, max_enemy_level: f64, min_enemy_level: f64, max_wave_num: f64, r#type: models::MissionType, nightmare: bool, archwing_required: bool, description: String) -> Mission {
        Mission {
            reward: Box::new(reward),
            node,
            node_key: None,
            faction,
            faction_key: None,
            max_enemy_level,
            min_enemy_level,
            max_wave_num,
            r#type,
            type_key: None,
            nightmare,
            archwing_required,
            is_sharkwing: None,
            enemy_spec: None,
            level_override: None,
            advanced_spawners: None,
            required_items: None,
            consume_required_items: None,
            leaders_always_allowed: None,
            level_auras: None,
            description,
        }
    }
}

