/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MissionTypes : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MissionTypes {
    #[serde(rename = "MT_EXCAVATE")]
    pub mt_excavate: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_SABOTAGE")]
    pub mt_sabotage: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_MOBILE_DEFENSE")]
    pub mt_mobile_defense: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_ASSASSINATION")]
    pub mt_assassination: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_EXTERMINATION")]
    pub mt_extermination: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_HIVE")]
    pub mt_hive: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_DEFENSE")]
    pub mt_defense: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_TERRITORY")]
    pub mt_territory: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_ARENA")]
    pub mt_arena: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_PVP")]
    pub mt_pvp: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_RESCUE")]
    pub mt_rescue: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_INTEL")]
    pub mt_intel: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_SURVIVAL")]
    pub mt_survival: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_CAPTURE")]
    pub mt_capture: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_SECTOR")]
    pub mt_sector: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_RETRIEVAL")]
    pub mt_retrieval: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_ASSAULT")]
    pub mt_assault: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_EVACUATION")]
    pub mt_evacuation: Box<models::ConclaveModesPvpmodeAll>,
}

impl MissionTypes {
    /// 
    pub fn new(mt_excavate: models::ConclaveModesPvpmodeAll, mt_sabotage: models::ConclaveModesPvpmodeAll, mt_mobile_defense: models::ConclaveModesPvpmodeAll, mt_assassination: models::ConclaveModesPvpmodeAll, mt_extermination: models::ConclaveModesPvpmodeAll, mt_hive: models::ConclaveModesPvpmodeAll, mt_defense: models::ConclaveModesPvpmodeAll, mt_territory: models::ConclaveModesPvpmodeAll, mt_arena: models::ConclaveModesPvpmodeAll, mt_pvp: models::ConclaveModesPvpmodeAll, mt_rescue: models::ConclaveModesPvpmodeAll, mt_intel: models::ConclaveModesPvpmodeAll, mt_survival: models::ConclaveModesPvpmodeAll, mt_capture: models::ConclaveModesPvpmodeAll, mt_sector: models::ConclaveModesPvpmodeAll, mt_retrieval: models::ConclaveModesPvpmodeAll, mt_assault: models::ConclaveModesPvpmodeAll, mt_evacuation: models::ConclaveModesPvpmodeAll) -> MissionTypes {
        MissionTypes {
            mt_excavate: Box::new(mt_excavate),
            mt_sabotage: Box::new(mt_sabotage),
            mt_mobile_defense: Box::new(mt_mobile_defense),
            mt_assassination: Box::new(mt_assassination),
            mt_extermination: Box::new(mt_extermination),
            mt_hive: Box::new(mt_hive),
            mt_defense: Box::new(mt_defense),
            mt_territory: Box::new(mt_territory),
            mt_arena: Box::new(mt_arena),
            mt_pvp: Box::new(mt_pvp),
            mt_rescue: Box::new(mt_rescue),
            mt_intel: Box::new(mt_intel),
            mt_survival: Box::new(mt_survival),
            mt_capture: Box::new(mt_capture),
            mt_sector: Box::new(mt_sector),
            mt_retrieval: Box::new(mt_retrieval),
            mt_assault: Box::new(mt_assault),
            mt_evacuation: Box::new(mt_evacuation),
        }
    }
}

