/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Mod {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "uniqueName", skip_serializing_if = "Option::is_none")]
    pub unique_name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "tradable", skip_serializing_if = "Option::is_none")]
    pub tradable: Option<bool>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(rename = "productCategory", skip_serializing_if = "Option::is_none")]
    pub product_category: Option<String>,
    #[serde(rename = "patchlogs", skip_serializing_if = "Option::is_none")]
    pub patchlogs: Option<Vec<models::Patchlog>>,
    #[serde(rename = "components", skip_serializing_if = "Option::is_none")]
    pub components: Option<Vec<models::ShallowItem>>,
    #[serde(rename = "introduced", skip_serializing_if = "Option::is_none")]
    pub introduced: Option<Box<models::Introduced>>,
    #[serde(rename = "estimatedVaultDate", skip_serializing_if = "Option::is_none")]
    pub estimated_vault_date: Option<String>,
    #[serde(rename = "baseDrain", skip_serializing_if = "Option::is_none")]
    pub base_drain: Option<i32>,
    #[serde(rename = "compatName", skip_serializing_if = "Option::is_none")]
    pub compat_name: Option<String>,
    #[serde(rename = "fusionLimit", skip_serializing_if = "Option::is_none")]
    pub fusion_limit: Option<i32>,
    #[serde(rename = "levelStats", skip_serializing_if = "Option::is_none")]
    pub level_stats: Option<Vec<models::ModAllOfLevelStats>>,
    #[serde(rename = "polarity", skip_serializing_if = "Option::is_none")]
    pub polarity: Option<models::Polarity>,
    #[serde(rename = "transmutable", skip_serializing_if = "Option::is_none")]
    pub transmutable: Option<bool>,
}

impl Mod {
    pub fn new() -> Mod {
        Mod {
            name: None,
            unique_name: None,
            description: None,
            r#type: None,
            tradable: None,
            category: None,
            product_category: None,
            patchlogs: None,
            components: None,
            introduced: None,
            estimated_vault_date: None,
            base_drain: None,
            compat_name: None,
            fusion_limit: None,
            level_stats: None,
            polarity: None,
            transmutable: None,
        }
    }
}

