/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewsInner {
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "imageLink")]
    pub image_link: String,
    #[serde(rename = "eta")]
    pub eta: String,
    #[serde(rename = "primeAccess")]
    pub prime_access: bool,
    #[serde(rename = "stream")]
    pub stream: bool,
    #[serde(rename = "translations", skip_serializing_if = "Option::is_none")]
    pub translations: Option<Box<models::NewsInnerTranslations>>,
    #[serde(rename = "link")]
    pub link: String,
    #[serde(rename = "update")]
    pub update: bool,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "asString")]
    pub as_string: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "priority")]
    pub priority: bool,
}

impl NewsInner {
    pub fn new(date: String, image_link: String, eta: String, prime_access: bool, stream: bool, link: String, update: bool, id: String, as_string: String, message: String, priority: bool) -> NewsInner {
        NewsInner {
            date,
            image_link,
            eta,
            prime_access,
            stream,
            translations: None,
            link,
            update,
            id,
            as_string,
            message,
            priority,
        }
    }
}

