/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OperatorLoadoutsInnerAbilityOverride {
    #[serde(rename = "ability", skip_serializing_if = "Option::is_none")]
    pub ability: Option<String>,
    #[serde(rename = "index", skip_serializing_if = "Option::is_none")]
    pub index: Option<i32>,
}

impl OperatorLoadoutsInnerAbilityOverride {
    pub fn new() -> OperatorLoadoutsInnerAbilityOverride {
        OperatorLoadoutsInnerAbilityOverride {
            ability: None,
            index: None,
        }
    }
}

