/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OperationTypes : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OperationTypes {
    #[serde(rename = "MULTIPLY")]
    pub multiply: Box<models::ConclaveModesPvpmodeAll>,
}

impl OperationTypes {
    /// 
    pub fn new(multiply: models::ConclaveModesPvpmodeAll) -> OperationTypes {
        OperationTypes {
            multiply: Box::new(multiply),
        }
    }
}

