/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaletteMatchesInnerPosition {
    #[serde(rename = "row", skip_serializing_if = "Option::is_none")]
    pub row: Option<i32>,
    #[serde(rename = "col", skip_serializing_if = "Option::is_none")]
    pub col: Option<i32>,
}

impl PaletteMatchesInnerPosition {
    pub fn new() -> PaletteMatchesInnerPosition {
        PaletteMatchesInnerPosition {
            row: None,
            col: None,
        }
    }
}

