/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaletteMatchesInner {
    #[serde(rename = "palette")]
    pub palette: Box<models::PaletteMatchesInnerPalette>,
    #[serde(rename = "position")]
    pub position: Box<models::PaletteMatchesInnerPosition>,
}

impl PaletteMatchesInner {
    pub fn new(palette: models::PaletteMatchesInnerPalette, position: models::PaletteMatchesInnerPosition) -> PaletteMatchesInner {
        PaletteMatchesInner {
            palette: Box::new(palette),
            position: Box::new(position),
        }
    }
}

