/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Polarity {
    #[serde(rename = "Vazarin")]
    Vazarin,
    #[serde(rename = "Madurai")]
    Madurai,
    #[serde(rename = "Naramon")]
    Naramon,
    #[serde(rename = "Zenurik")]
    Zenurik,
    #[serde(rename = "Unairu")]
    Unairu,
    #[serde(rename = "Penjaga")]
    Penjaga,
    #[serde(rename = "Unbra")]
    Unbra,

}

impl std::fmt::Display for Polarity {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Vazarin => write!(f, "Vazarin"),
            Self::Madurai => write!(f, "Madurai"),
            Self::Naramon => write!(f, "Naramon"),
            Self::Zenurik => write!(f, "Zenurik"),
            Self::Unairu => write!(f, "Unairu"),
            Self::Penjaga => write!(f, "Penjaga"),
            Self::Unbra => write!(f, "Unbra"),
        }
    }
}

impl Default for Polarity {
    fn default() -> Polarity {
        Self::Vazarin
    }
}

