/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileIntrinsics {
    #[serde(rename = "railjack", skip_serializing_if = "Option::is_none")]
    pub railjack: Option<i32>,
    #[serde(rename = "engineering", skip_serializing_if = "Option::is_none")]
    pub engineering: Option<i32>,
    #[serde(rename = "gunnery", skip_serializing_if = "Option::is_none")]
    pub gunnery: Option<i32>,
    #[serde(rename = "piloting", skip_serializing_if = "Option::is_none")]
    pub piloting: Option<i32>,
    #[serde(rename = "tactical", skip_serializing_if = "Option::is_none")]
    pub tactical: Option<i32>,
    #[serde(rename = "command", skip_serializing_if = "Option::is_none")]
    pub command: Option<i32>,
    #[serde(rename = "drifter", skip_serializing_if = "Option::is_none")]
    pub drifter: Option<i32>,
    #[serde(rename = "riding", skip_serializing_if = "Option::is_none")]
    pub riding: Option<i32>,
    #[serde(rename = "combat", skip_serializing_if = "Option::is_none")]
    pub combat: Option<i32>,
    #[serde(rename = "opportunity", skip_serializing_if = "Option::is_none")]
    pub opportunity: Option<i32>,
    #[serde(rename = "endurance", skip_serializing_if = "Option::is_none")]
    pub endurance: Option<i32>,
}

impl ProfileIntrinsics {
    pub fn new() -> ProfileIntrinsics {
        ProfileIntrinsics {
            railjack: None,
            engineering: None,
            gunnery: None,
            piloting: None,
            tactical: None,
            command: None,
            drifter: None,
            riding: None,
            combat: None,
            opportunity: None,
            endurance: None,
        }
    }
}

