/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SentientOutpostsMission {
    /// Localized node name
    #[serde(rename = "node")]
    pub node: String,
    #[serde(rename = "type")]
    pub r#type: models::MissionType,
    #[serde(rename = "faction")]
    pub faction: models::Faction,
}

impl SentientOutpostsMission {
    pub fn new(node: String, r#type: models::MissionType, faction: models::Faction) -> SentientOutpostsMission {
        SentientOutpostsMission {
            node,
            r#type,
            faction,
        }
    }
}

