/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SlamAttackRadial {
    #[serde(rename = "damage", skip_serializing_if = "Option::is_none")]
    pub damage: Option<f32>,
    #[serde(rename = "element", skip_serializing_if = "Option::is_none")]
    pub element: Option<models::Element>,
    #[serde(rename = "proc", skip_serializing_if = "Option::is_none")]
    pub proc: Option<f32>,
    #[serde(rename = "radius", skip_serializing_if = "Option::is_none")]
    pub radius: Option<f32>,
}

impl SlamAttackRadial {
    pub fn new() -> SlamAttackRadial {
        SlamAttackRadial {
            damage: None,
            element: None,
            proc: None,
            radius: None,
        }
    }
}

