/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SortieDataModifierTypes {
    #[serde(rename = "SORTIE_MODIFIER_IMPACT")]
    pub sortie_modifier_impact: String,
    #[serde(rename = "SORTIE_MODIFIER_HAZARD_COLD")]
    pub sortie_modifier_hazard_cold: String,
    #[serde(rename = "SORTIE_MODIFIER_SECONDARY_ONLY")]
    pub sortie_modifier_secondary_only: String,
    #[serde(rename = "SORTIE_MODIFIER_TOXIN")]
    pub sortie_modifier_toxin: String,
    #[serde(rename = "SORTIE_MODIFIER_ELECTRICITY")]
    pub sortie_modifier_electricity: String,
    #[serde(rename = "SORTIE_MODIFIER_HAZARD_FOG")]
    pub sortie_modifier_hazard_fog: String,
    #[serde(rename = "SORTIE_MODIFIER_HAZARD_MAGNETIC")]
    pub sortie_modifier_hazard_magnetic: String,
    #[serde(rename = "SORTIE_MODIFIER_ARMOR")]
    pub sortie_modifier_armor: String,
    #[serde(rename = "SORTIE_MODIFIER_CORROSIVE")]
    pub sortie_modifier_corrosive: String,
    #[serde(rename = "SORTIE_MODIFIER_VIRAL")]
    pub sortie_modifier_viral: String,
    #[serde(rename = "SORTIE_MODIFIER_HAZARD_RADIATION")]
    pub sortie_modifier_hazard_radiation: String,
    #[serde(rename = "SORTIE_MODIFIER_SLASH")]
    pub sortie_modifier_slash: String,
    #[serde(rename = "SORTIE_MODIFIER_POISON")]
    pub sortie_modifier_poison: String,
    #[serde(rename = "SORTIE_MODIFIER_GAS")]
    pub sortie_modifier_gas: String,
    #[serde(rename = "SORTIE_MODIFIER_MAGNETIC")]
    pub sortie_modifier_magnetic: String,
    #[serde(rename = "SORTIE_MODIFIER_FIRE")]
    pub sortie_modifier_fire: String,
    #[serde(rename = "SORTIE_MODIFIER_SNIPER_ONLY")]
    pub sortie_modifier_sniper_only: String,
    #[serde(rename = "SORTIE_MODIFIER_PUNCTURE")]
    pub sortie_modifier_puncture: String,
    #[serde(rename = "SORTIE_MODIFIER_EXPLOSION")]
    pub sortie_modifier_explosion: String,
    #[serde(rename = "SORTIE_MODIFIER_BOW_ONLY")]
    pub sortie_modifier_bow_only: String,
    #[serde(rename = "SORTIE_MODIFIER_RADIATION")]
    pub sortie_modifier_radiation: String,
    #[serde(rename = "SORTIE_MODIFIER_SHIELDS")]
    pub sortie_modifier_shields: String,
    #[serde(rename = "SORTIE_MODIFIER_FREEZE")]
    pub sortie_modifier_freeze: String,
    #[serde(rename = "SORTIE_MODIFIER_HAZARD_FIRE")]
    pub sortie_modifier_hazard_fire: String,
    #[serde(rename = "SORTIE_MODIFIER_EXIMUS")]
    pub sortie_modifier_eximus: String,
    #[serde(rename = "SORTIE_MODIFIER_SHOTGUN_ONLY")]
    pub sortie_modifier_shotgun_only: String,
    #[serde(rename = "SORTIE_MODIFIER_MELEE_ONLY")]
    pub sortie_modifier_melee_only: String,
    #[serde(rename = "SORTIE_MODIFIER_RIFLE_ONLY")]
    pub sortie_modifier_rifle_only: String,
    #[serde(rename = "SORTIE_MODIFIER_HAZARD_ICE")]
    pub sortie_modifier_hazard_ice: String,
    #[serde(rename = "SORTIE_MODIFIER_LOW_ENERGY")]
    pub sortie_modifier_low_energy: String,
}

impl SortieDataModifierTypes {
    pub fn new(sortie_modifier_impact: String, sortie_modifier_hazard_cold: String, sortie_modifier_secondary_only: String, sortie_modifier_toxin: String, sortie_modifier_electricity: String, sortie_modifier_hazard_fog: String, sortie_modifier_hazard_magnetic: String, sortie_modifier_armor: String, sortie_modifier_corrosive: String, sortie_modifier_viral: String, sortie_modifier_hazard_radiation: String, sortie_modifier_slash: String, sortie_modifier_poison: String, sortie_modifier_gas: String, sortie_modifier_magnetic: String, sortie_modifier_fire: String, sortie_modifier_sniper_only: String, sortie_modifier_puncture: String, sortie_modifier_explosion: String, sortie_modifier_bow_only: String, sortie_modifier_radiation: String, sortie_modifier_shields: String, sortie_modifier_freeze: String, sortie_modifier_hazard_fire: String, sortie_modifier_eximus: String, sortie_modifier_shotgun_only: String, sortie_modifier_melee_only: String, sortie_modifier_rifle_only: String, sortie_modifier_hazard_ice: String, sortie_modifier_low_energy: String) -> SortieDataModifierTypes {
        SortieDataModifierTypes {
            sortie_modifier_impact,
            sortie_modifier_hazard_cold,
            sortie_modifier_secondary_only,
            sortie_modifier_toxin,
            sortie_modifier_electricity,
            sortie_modifier_hazard_fog,
            sortie_modifier_hazard_magnetic,
            sortie_modifier_armor,
            sortie_modifier_corrosive,
            sortie_modifier_viral,
            sortie_modifier_hazard_radiation,
            sortie_modifier_slash,
            sortie_modifier_poison,
            sortie_modifier_gas,
            sortie_modifier_magnetic,
            sortie_modifier_fire,
            sortie_modifier_sniper_only,
            sortie_modifier_puncture,
            sortie_modifier_explosion,
            sortie_modifier_bow_only,
            sortie_modifier_radiation,
            sortie_modifier_shields,
            sortie_modifier_freeze,
            sortie_modifier_hazard_fire,
            sortie_modifier_eximus,
            sortie_modifier_shotgun_only,
            sortie_modifier_melee_only,
            sortie_modifier_rifle_only,
            sortie_modifier_hazard_ice,
            sortie_modifier_low_energy,
        }
    }
}

