/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SortieDataBosses {
    #[serde(rename = "SORTIE_BOSS_KELA")]
    pub sortie_boss_kela: Box<models::SortieDataBossesSortieBossKela>,
    #[serde(rename = "SORTIE_BOSS_AMBULAS")]
    pub sortie_boss_ambulas: Box<models::SortieDataBossesSortieBossKela>,
    #[serde(rename = "SORTIE_BOSS_TYL")]
    pub sortie_boss_tyl: Box<models::SortieDataBossesSortieBossKela>,
    #[serde(rename = "SORTIE_BOSS_ALAD")]
    pub sortie_boss_alad: Box<models::SortieDataBossesSortieBossKela>,
    #[serde(rename = "SORTIE_BOSS_RUK")]
    pub sortie_boss_ruk: Box<models::SortieDataBossesSortieBossKela>,
    #[serde(rename = "SORTIE_BOSS_HYENA")]
    pub sortie_boss_hyena: Box<models::SortieDataBossesSortieBossKela>,
    #[serde(rename = "SORTIE_BOSS_KRIL")]
    pub sortie_boss_kril: Box<models::SortieDataBossesSortieBossKela>,
    #[serde(rename = "SORTIE_BOSS_CORRUPTED_VOR")]
    pub sortie_boss_corrupted_vor: Box<models::SortieDataBossesSortieBossKela>,
    #[serde(rename = "SORTIE_BOSS_INFALAD")]
    pub sortie_boss_infalad: Box<models::SortieDataBossesSortieBossKela>,
    #[serde(rename = "SORTIE_BOSS_PHORID")]
    pub sortie_boss_phorid: Box<models::SortieDataBossesSortieBossKela>,
    #[serde(rename = "SORTIE_BOSS_JACKAL")]
    pub sortie_boss_jackal: Box<models::SortieDataBossesSortieBossKela>,
    #[serde(rename = "SORTIE_BOSS_RAPTOR")]
    pub sortie_boss_raptor: Box<models::SortieDataBossesSortieBossKela>,
    #[serde(rename = "SORTIE_BOSS_VOR")]
    pub sortie_boss_vor: Box<models::SortieDataBossesSortieBossKela>,
    #[serde(rename = "SORTIE_BOSS_HEK")]
    pub sortie_boss_hek: Box<models::SortieDataBossesSortieBossKela>,
    #[serde(rename = "SORTIE_BOSS_NEF")]
    pub sortie_boss_nef: Box<models::SortieDataBossesSortieBossKela>,
    #[serde(rename = "SORTIE_BOSS_LEPHANTIS")]
    pub sortie_boss_lephantis: Box<models::SortieDataBossesSortieBossKela>,
}

impl SortieDataBosses {
    pub fn new(sortie_boss_kela: models::SortieDataBossesSortieBossKela, sortie_boss_ambulas: models::SortieDataBossesSortieBossKela, sortie_boss_tyl: models::SortieDataBossesSortieBossKela, sortie_boss_alad: models::SortieDataBossesSortieBossKela, sortie_boss_ruk: models::SortieDataBossesSortieBossKela, sortie_boss_hyena: models::SortieDataBossesSortieBossKela, sortie_boss_kril: models::SortieDataBossesSortieBossKela, sortie_boss_corrupted_vor: models::SortieDataBossesSortieBossKela, sortie_boss_infalad: models::SortieDataBossesSortieBossKela, sortie_boss_phorid: models::SortieDataBossesSortieBossKela, sortie_boss_jackal: models::SortieDataBossesSortieBossKela, sortie_boss_raptor: models::SortieDataBossesSortieBossKela, sortie_boss_vor: models::SortieDataBossesSortieBossKela, sortie_boss_hek: models::SortieDataBossesSortieBossKela, sortie_boss_nef: models::SortieDataBossesSortieBossKela, sortie_boss_lephantis: models::SortieDataBossesSortieBossKela) -> SortieDataBosses {
        SortieDataBosses {
            sortie_boss_kela: Box::new(sortie_boss_kela),
            sortie_boss_ambulas: Box::new(sortie_boss_ambulas),
            sortie_boss_tyl: Box::new(sortie_boss_tyl),
            sortie_boss_alad: Box::new(sortie_boss_alad),
            sortie_boss_ruk: Box::new(sortie_boss_ruk),
            sortie_boss_hyena: Box::new(sortie_boss_hyena),
            sortie_boss_kril: Box::new(sortie_boss_kril),
            sortie_boss_corrupted_vor: Box::new(sortie_boss_corrupted_vor),
            sortie_boss_infalad: Box::new(sortie_boss_infalad),
            sortie_boss_phorid: Box::new(sortie_boss_phorid),
            sortie_boss_jackal: Box::new(sortie_boss_jackal),
            sortie_boss_raptor: Box::new(sortie_boss_raptor),
            sortie_boss_vor: Box::new(sortie_boss_vor),
            sortie_boss_hek: Box::new(sortie_boss_hek),
            sortie_boss_nef: Box::new(sortie_boss_nef),
            sortie_boss_lephantis: Box::new(sortie_boss_lephantis),
        }
    }
}

