/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Sortie {
    /// unique identifier for this object/event/thing
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// ISO-8601 formatted timestamp for when the event began
    #[serde(rename = "activation", skip_serializing_if = "Option::is_none")]
    pub activation: Option<String>,
    /// A timestamp in ISO 8601 format (YYYY-MM-DDTHH:MM:SSZ) representing a specific point in time. This format is commonly used in APIs to ensure consistent date and time representation. The timestamp is in UTC (Coordinated Universal Time) and does not include any timezone offset. It is used to represent events, deadlines, or any time-related information in a standardized way. Example: \"2023-10-01T12:00:00Z\" represents October 1, 2023, at 12:00 PM UTC. 
    #[serde(rename = "expiry", skip_serializing_if = "Option::is_none")]
    pub expiry: Option<String>,
    #[serde(rename = "rewardPool")]
    pub reward_pool: String,
    #[serde(rename = "variants")]
    pub variants: Vec<models::SortieAllOfVariants>,
    #[serde(rename = "boss")]
    pub boss: String,
    /// Faction of the boss controlling the sortie
    #[serde(rename = "faction")]
    pub faction: models::Faction,
    /// Unlocalized Faction of the boss controlling the sortie
    #[serde(rename = "factionKey", skip_serializing_if = "Option::is_none")]
    pub faction_key: Option<models::Faction>,
}

impl Sortie {
    pub fn new(reward_pool: String, variants: Vec<models::SortieAllOfVariants>, boss: String, faction: models::Faction) -> Sortie {
        Sortie {
            id: None,
            activation: None,
            expiry: None,
            reward_pool,
            variants,
            boss,
            faction,
            faction_key: None,
        }
    }
}

