/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsPvpInner {
    #[serde(rename = "uniqueName", skip_serializing_if = "Option::is_none")]
    pub unique_name: Option<String>,
    #[serde(rename = "suitDeaths", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub suit_deaths: Option<Option<i32>>,
    #[serde(rename = "suitKills", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub suit_kills: Option<Option<i32>>,
    #[serde(rename = "weaponKills", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub weapon_kills: Option<Option<i32>>,
}

impl StatsPvpInner {
    pub fn new() -> StatsPvpInner {
        StatsPvpInner {
            unique_name: None,
            suit_deaths: None,
            suit_kills: None,
            weapon_kills: None,
        }
    }
}

