/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsWeaponsInner {
    #[serde(rename = "uniqueName")]
    pub unique_name: String,
    #[serde(rename = "xp")]
    pub xp: i32,
    #[serde(rename = "equipTime")]
    pub equip_time: f64,
    #[serde(rename = "assists")]
    pub assists: i32,
    #[serde(rename = "kills")]
    pub kills: i32,
    #[serde(rename = "fired")]
    pub fired: i32,
}

impl StatsWeaponsInner {
    pub fn new(unique_name: String, xp: i32, equip_time: f64, assists: i32, kills: i32, fired: i32) -> StatsWeaponsInner {
        StatsWeaponsInner {
            unique_name,
            xp,
            equip_time,
            assists,
            kills,
            fired,
        }
    }
}

