/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsEnemisInner {
    #[serde(rename = "uniqueName")]
    pub unique_name: String,
    #[serde(rename = "kills")]
    pub kills: i32,
    #[serde(rename = "headshots")]
    pub headshots: i32,
}

impl StatsEnemisInner {
    pub fn new(unique_name: String, kills: i32, headshots: i32) -> StatsEnemisInner {
        StatsEnemisInner {
            unique_name,
            kills,
            headshots,
        }
    }
}

