/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsScarletSpear {
    #[serde(rename = "eventScore", skip_serializing_if = "Option::is_none")]
    pub event_score: Option<i32>,
    #[serde(rename = "condirxTier2", skip_serializing_if = "Option::is_none")]
    pub condirx_tier2: Option<i32>,
    #[serde(rename = "murexTier1", skip_serializing_if = "Option::is_none")]
    pub murex_tier1: Option<i32>,
    #[serde(rename = "murexTier2", skip_serializing_if = "Option::is_none")]
    pub murex_tier2: Option<i32>,
    #[serde(rename = "murexTier3", skip_serializing_if = "Option::is_none")]
    pub murex_tier3: Option<i32>,
}

impl StatsScarletSpear {
    pub fn new() -> StatsScarletSpear {
        StatsScarletSpear {
            event_score: None,
            condirx_tier2: None,
            murex_tier1: None,
            murex_tier2: None,
            murex_tier3: None,
        }
    }
}

