/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsLunaro {
    #[serde(rename = "ties", skip_serializing_if = "Option::is_none")]
    pub ties: Option<i32>,
    #[serde(rename = "checks", skip_serializing_if = "Option::is_none")]
    pub checks: Option<i32>,
    #[serde(rename = "goals", skip_serializing_if = "Option::is_none")]
    pub goals: Option<i32>,
    #[serde(rename = "interceptions", skip_serializing_if = "Option::is_none")]
    pub interceptions: Option<i32>,
    #[serde(rename = "steals", skip_serializing_if = "Option::is_none")]
    pub steals: Option<i32>,
    #[serde(rename = "points", skip_serializing_if = "Option::is_none")]
    pub points: Option<i32>,
    #[serde(rename = "losses", skip_serializing_if = "Option::is_none")]
    pub losses: Option<i32>,
}

impl StatsLunaro {
    pub fn new() -> StatsLunaro {
        StatsLunaro {
            ties: None,
            checks: None,
            goals: None,
            interceptions: None,
            steals: None,
            points: None,
            losses: None,
        }
    }
}

