/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsAbilitiesInner {
    #[serde(rename = "uniqueName")]
    pub unique_name: String,
    #[serde(rename = "used")]
    pub used: i32,
}

impl StatsAbilitiesInner {
    pub fn new(unique_name: String, used: i32) -> StatsAbilitiesInner {
        StatsAbilitiesInner {
            unique_name,
            used,
        }
    }
}

