/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Syndicates : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Syndicates {
    #[serde(rename = "ArbitersSyndicate")]
    pub arbiters_syndicate: Box<models::SyndicatesArbitersSyndicate>,
    #[serde(rename = "CephalonSudaSyndicate")]
    pub cephalon_suda_syndicate: Box<models::SyndicatesArbitersSyndicate>,
    #[serde(rename = "NewLokaSyndicate")]
    pub new_loka_syndicate: Box<models::SyndicatesArbitersSyndicate>,
    #[serde(rename = "PerrinSyndicate")]
    pub perrin_syndicate: Box<models::SyndicatesArbitersSyndicate>,
    #[serde(rename = "SteelMeridianSyndicate")]
    pub steel_meridian_syndicate: Box<models::SyndicatesArbitersSyndicate>,
    #[serde(rename = "RedVeilSyndicate")]
    pub red_veil_syndicate: Box<models::SyndicatesArbitersSyndicate>,
    #[serde(rename = "CetusSyndicate")]
    pub cetus_syndicate: Box<models::SyndicatesArbitersSyndicate>,
    #[serde(rename = "QuillsSyndicate")]
    pub quills_syndicate: Box<models::SyndicatesArbitersSyndicate>,
    #[serde(rename = "AssassinsSyndicate")]
    pub assassins_syndicate: Box<models::SyndicatesArbitersSyndicate>,
    #[serde(rename = "EventSyndicate")]
    pub event_syndicate: Box<models::SyndicatesArbitersSyndicate>,
}

impl Syndicates {
    /// 
    pub fn new(arbiters_syndicate: models::SyndicatesArbitersSyndicate, cephalon_suda_syndicate: models::SyndicatesArbitersSyndicate, new_loka_syndicate: models::SyndicatesArbitersSyndicate, perrin_syndicate: models::SyndicatesArbitersSyndicate, steel_meridian_syndicate: models::SyndicatesArbitersSyndicate, red_veil_syndicate: models::SyndicatesArbitersSyndicate, cetus_syndicate: models::SyndicatesArbitersSyndicate, quills_syndicate: models::SyndicatesArbitersSyndicate, assassins_syndicate: models::SyndicatesArbitersSyndicate, event_syndicate: models::SyndicatesArbitersSyndicate) -> Syndicates {
        Syndicates {
            arbiters_syndicate: Box::new(arbiters_syndicate),
            cephalon_suda_syndicate: Box::new(cephalon_suda_syndicate),
            new_loka_syndicate: Box::new(new_loka_syndicate),
            perrin_syndicate: Box::new(perrin_syndicate),
            steel_meridian_syndicate: Box::new(steel_meridian_syndicate),
            red_veil_syndicate: Box::new(red_veil_syndicate),
            cetus_syndicate: Box::new(cetus_syndicate),
            quills_syndicate: Box::new(quills_syndicate),
            assassins_syndicate: Box::new(assassins_syndicate),
            event_syndicate: Box::new(event_syndicate),
        }
    }
}

