/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpgradeTypes : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpgradeTypes {
    #[serde(rename = "GAMEPLAY_KILL_XP_AMOUNT")]
    pub gameplay_kill_xp_amount: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "GAMEPLAY_PICKUP_AMOUNT")]
    pub gameplay_pickup_amount: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "GAMEPLAY_MONEY_REWARD_AMOUNT")]
    pub gameplay_money_reward_amount: Box<models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "GAMEPLAY_MONEY_PICKUP_AMOUNT")]
    pub gameplay_money_pickup_amount: Box<models::ConclaveModesPvpmodeAll>,
}

impl UpgradeTypes {
    /// 
    pub fn new(gameplay_kill_xp_amount: models::ConclaveModesPvpmodeAll, gameplay_pickup_amount: models::ConclaveModesPvpmodeAll, gameplay_money_reward_amount: models::ConclaveModesPvpmodeAll, gameplay_money_pickup_amount: models::ConclaveModesPvpmodeAll) -> UpgradeTypes {
        UpgradeTypes {
            gameplay_kill_xp_amount: Box::new(gameplay_kill_xp_amount),
            gameplay_pickup_amount: Box::new(gameplay_pickup_amount),
            gameplay_money_reward_amount: Box::new(gameplay_money_reward_amount),
            gameplay_money_pickup_amount: Box::new(gameplay_money_pickup_amount),
        }
    }
}

