/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VallisCycle {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "expiry")]
    pub expiry: String,
    #[serde(rename = "timeLeft")]
    pub time_left: String,
    #[serde(rename = "isWarm")]
    pub is_warm: bool,
}

impl VallisCycle {
    pub fn new(id: String, expiry: String, time_left: String, is_warm: bool) -> VallisCycle {
        VallisCycle {
            id,
            expiry,
            time_left,
            is_warm,
        }
    }
}

