/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VoidTrader {
    /// unique identifier for this object/event/thing
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// ISO-8601 formatted timestamp for when the event began
    #[serde(rename = "activation", skip_serializing_if = "Option::is_none")]
    pub activation: Option<String>,
    /// A timestamp in ISO 8601 format (YYYY-MM-DDTHH:MM:SSZ) representing a specific point in time. This format is commonly used in APIs to ensure consistent date and time representation. The timestamp is in UTC (Coordinated Universal Time) and does not include any timezone offset. It is used to represent events, deadlines, or any time-related information in a standardized way. Example: \"2023-10-01T12:00:00Z\" represents October 1, 2023, at 12:00 PM UTC. 
    #[serde(rename = "expiry", skip_serializing_if = "Option::is_none")]
    pub expiry: Option<String>,
    #[serde(rename = "character")]
    pub character: String,
    #[serde(rename = "location")]
    pub location: String,
    #[serde(rename = "inventory")]
    pub inventory: Vec<models::VoidTraderAllOfInventory>,
    #[serde(rename = "psId")]
    pub ps_id: String,
    #[serde(rename = "active")]
    pub active: bool,
    #[serde(rename = "startString")]
    pub start_string: String,
    #[serde(rename = "endString")]
    pub end_string: String,
}

impl VoidTrader {
    pub fn new(character: String, location: String, inventory: Vec<models::VoidTraderAllOfInventory>, ps_id: String, active: bool, start_string: String, end_string: String) -> VoidTrader {
        VoidTrader {
            id: None,
            activation: None,
            expiry: None,
            character,
            location,
            inventory,
            ps_id,
            active,
            start_string,
            end_string,
        }
    }
}

