/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WeaponsInner {
    RangedWeapon(Box<models::RangedWeapon>),
    MeleeWeapon(Box<models::MeleeWeapon>),
}

impl Default for WeaponsInner {
    fn default() -> Self {
        Self::RangedWeapon(Default::default())
    }
}

